"use strict";

/*************************
 * Translation Engine for KWM App
 * Just add your Key:Value Pairs and enjoy
 *************************/
export default class KWM_Translator {
    constructor(languages) {
        for (const lng of languages) {
            this[lng] = KWM_Language[lng];
        }
        this.currentLanguage = window.Core.utils.getCookie("language") ? window.Core.utils.getCookie("language") : languages[0];
    }

    t(key, language = this.currentLanguage) {
        return (typeof KWM_Language[language][key] == "undefined") ? "-- Missing translation: " + key + " --" : KWM_Language[language][key];
    }
}

let KWM_Language = {};
KWM_Language.en = {
    welcomeMessage: "Welcome to Petcare",
    logout: "logout",
    login: "Login",
    password: "Password",
    username: "Username",
    name: "Name",
    footer_text: "We at Petcare take care of abandoned and found pets. With us they get everything they need, such as food and cuddles, but above all a roof over their heads - a temporary home. Many of our animals are happy to meet new loving owners and to be taken in as a new family member. Find your suitable pet on Petcare and give a hand for a paw.",
    footer_aboutUs: "About us",
    footer_contact: "Contact",
    footer_termsAndConditions: "Terms and Conditions",
    footer_privacyPolicy: "Privacy Policy",
    footer_newsletter: "Newsletter",
    footer_newsletterDescription: "Subscribe to our newsletter and receive the latest pet news from Petcare ...",
    footer_newsletterPlaceholder: "email address",
    footer_rightsReserved: "All rights reserved.",
    pets: "Pets",
    cats: "Cats",
    dogs: "Dogs",
    hamster: "Hamster",
    fish: "fish",
    rabbits: "Rabbits",
    home: "Home",
    register: "Register",
    home_petcare_h1: "Petcare - we help pets in need",
    donate: "Donate",
    show_more_cats: "show more cats",
    show_more_dogs: "show more dogs",
    this_is: "This is",
    is: "is",
    old_and_is_looking_for_a_new_home: "old and is looking for a new home",
    about_me: "About me",
    some_facts_on_me: "Some facts on me",
    gender: "Gender",
    color: "Color",
    age: "Age",
    years: "years",
    coat: "Coat",
    weight: "weight",
    favourite_food: "Favourite Food",
    yummy: "*yummy*",
    playfullness: "Playfullness",
    activity_level: "Activity Level",
    give_me_a_home: "give me a home",
    size: "Size",
    characteristics: "Characteristics",
    hello_iam: "Hello, I'm",
    email: "E-Mail",
    adopt: "Adopt",
    a_cat: "a Cat",
    a_dog: "a Dog",
    a_pet: "a Pet",
    comments: "Comments",
    send: "Send",
    what_do_you_want_to_know_about: "What do you want to know about",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    select: "Select ...",
    male: "male",
    female: "female",
    low : "low",
    medium : "medium",
    high : "high",
    short : "short",
    long : "long",
    show_all : "show all",
    all : "All",
    dont_have_an_account : "Don't have an account?",
    already_have_an_account : "Already have an account?",
    to_delete_comment_just_click_it : "to delete a comment just click on it",
};
KWM_Language.de = {
    welcomeMessage: "Willkommen bei Petcare",
    logout: "abmelden",
    login: "Anmelden",
    password: "Passwort",
    username: "Benutzername",
    name: "Name",
    footer_text: "Wir von Petcare kümmern uns um abgegebene und aufgefundene Haustiere. Bei uns bekommen sie alles was sie benötigen, wie etwa Futter und Streicheleinheiten aber vor allem ein Dach über dem Kopf - ein zuhause auf Zeit. Viele unserer Tiere freuen sich, neue liebevolle Besitzer kennenzulernen und als neues Familienmitglied aufgenommen zu werden. Finde auch du dein passendes Haustier auf Petcare und reiche einer Pfote deine Hand.",
    footer_aboutUs: "&Uuml;ber uns",
    footer_contact: "Kontakt",
    footer_termsAndConditions: "AGB",
    footer_privacyPolicy: "Datenschutzerklärung",
    footer_newsletter: "Newsletter",
    footer_newsletterDescription: "Abonnieren Sie unseren Newsletter und erhalten Sie aktuelle Haustiernews von Petcare ...",
    footer_newsletterPlaceholder: "E-Mail Adresse",
    footer_rightsReserved: "Alle Rechte vorbehalten.",
    pets: "Haustiere",
    cats: "Katzen",
    dogs: "Hunde",
    hamster: "Hamster",
    fish: "Fisch",
    rabbits: "Hasen",
    home: "Startseite",
    register: "Registrieren",
    home_petcare_h1: "Petcare - wir helfen Haustieren in Not",
    donate: "Spenden",
    show_more_cats: "mehr Katzen anzeigen",
    show_more_dogs: "mehr Hunde anzeigen",
    this_is: "Das ist",
    is: "ist",
    old_and_is_looking_for_a_new_home: "alt und auf der Suche nach einem neuen zuhause",
    about_me: "Über mich",
    some_facts_on_me: "Einige Fakten über mich",
    gender: "Geschlecht",
    color: "Farbe",
    age: "Alter",
    years: "Jahre",
    coat: "Fell",
    weight: "Gewicht",
    favourite_food: "Lieblingesessen",
    yummy: "*lecker*",
    playfullness: "Verspieltheit",
    activity_level: "Aktivit&auml;tslevel",
    give_me_a_home: "gib mir ein zuhause",
    size: "Größe",
    characteristics: "Charakteristik",
    hello_iam: "Hallo, ich bin",
    email: "E-Mail",
    adopt: "Adoptiere",
    a_cat: "eine Katze",
    a_dog: "einen Hund",
    a_pet: "ein Haustier",
    comments: "Kommentare",
    send: "Absenden",
    what_do_you_want_to_know_about: "Was möchtest du wissen über",
    sort: "Sortierung",
    ascending: "Aufsteigend",
    descending: "Absteigend",
    select: "Auswählen ...",
    male: "männlich",
    female: "weiblich",
    low : "niedrig",
    medium : "mittel",
    high : "hoch",
    short : "kurz",
    long : "lang",
    show_all : "alle anzeigen",
    all : "Alle",
    dont_have_an_account : "Noch kein Account?",
    already_have_an_account : "Bereits registriert?",
    to_delete_comment_just_click_it : "um einen Kommentar zu löschen klicke diesen einfach an",

};
KWM_Language.es = {
    welcomeMessage: "Bienvenidos a Petcare",
    logout: "desconexión",
    login: "Acceso",
    password: "Contraseña",
    username: "Usario",
    name: "Nombré",
    footer_text: "En Petcare nos ocupamos de las mascotas abandonadas y encontradas. Con nosotros reciben todo lo que necesitan, como comida y mimos, pero sobre todo un techo, un hogar temporal. Muchos de nuestros animales están encantados de conocer a nuevos dueños cariñosos y de ser acogidos como un nuevo miembro de la familia. Encuentra la mascota adecuada para ti en Petcare y dale la mano a una pata.",
    footer_aboutUs: "Sobre nosotros",
    footer_contact: "Contacto",
    footer_termsAndConditions: "Condiciones de Contración",
    footer_privacyPolicy: "Declaración de Privacidad",
    footer_newsletter: "boletín electrónico",
    footer_newsletterDescription: "Suscríbase a nuestro boletín de noticias y reciba las últimas novedades de Petcare ...",
    footer_newsletterPlaceholder: "dirección de mail",
    footer_rightsReserved: "Todos los derechos reservados.",
    pets: "Mascotase",
    cats: "Gatos",
    dogs: "Perros",
    hamster: "Hámster",
    fish: "Pescado",
    rabbits: "Conejos",
    home: "Página inicial",
    register: "Registro",
    home_petcare_h1: "Petcare - ayudamos a las mascotas necesitadas",
    donate: "Donar",
    show_more_cats: "mostrar más gatos",
    show_more_dogs: "mostrar más perros",
    this_is: "Se trata de",
    is: "tienes",
    old_and_is_looking_for_a_new_home: "y está buscando un nuevo hogar",
    about_me: "Sobre mí",
    some_facts_on_me: "Datos sobre mí",
    gender: "Género",
    color: "Color",
    age: "Edad",
    years: "años",
    coat: "Pieles",
    weight: "Peso",
    favourite_food: "Plato favorito",
    yummy: "*que rico*",
    playfullness: "Juguetón",
    activity_level: "Nivel de actividad",
    give_me_a_home: "dame un hogar",
    size: "Tamaño",
    characteristics: "Características",
    hello_iam: "Hola, soy",
    email: "Dirección de e-mail",
    adopt: "Adoptar",
    a_cat: "un Gato",
    a_dog: "un Perro",
    a_pet: "una mascota",
    comments: "Comentarios",
    send: "Publicar",
    what_do_you_want_to_know_about: "Qué quieres saber sobre",
    sort: "Clasificación",
    ascending: "Ascendente",
    descending: "Descendente",
    select: "Seleccione ...",
    male: "masculino",
    female: "femenino",
    low : "bajo",
    medium : "mediuo",
    high : "alto",
    short : "corto",
    long : "largo",
    show_all : "monstrar todos",
    all : "Todos",
    dont_have_an_account : "No tiene una cuenta?",
    already_have_an_account : "Ya tiene una cuenta?",
    to_delete_comment_just_click_it : "para borrar un comentario basta con hacer clic en él",

};